### ISSUE TITLE
[Bug Report]: Stunning visual bug

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungonesArtifacts#29]
### Describe the bug; What happened?

when the player is under the effects of the Stunning status effect, their face is prevented from changing it's horizontal rotation, but the rest of their body is not, allowing the head to appear "backwards" in relation to the body

### Expected Behavior

either the player is not supposed to be able to rotate their camera while under the effects of stunned, the player's body rotation should be locked just like the head or the player's head should not have it's rotation locked at all

### Mod Version

6.0.4

### Minecraft Launcher

Other

### Operating System

Linux

### Additional context

the primary way to be under the Stunned status condition long enough to really notice this bug is if another player is wearing several armor pieces enchanted with Cooldown and repeatedly using an Light Feather, or having the stunning condition applied via command. Noticed this bug using the former method, for all i know it could be slightly different if Stunned is applied via feather

**Comment by chronosacaria** [comment]
So, the reason for not doing this, though it was considered, was so that players do not think that there is a crash or bug happening. This is especially important for players who rely on vision to play Minecraft (i.e. those who have hearing impairments). I'll close this issue for the time being, but it will be considered if the concern is raised again
